# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Abhiram Balasubramanian
tagline:             ''
description:         ''
url:                 http://abhirambal.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Srinath Sridhar
  url:               
  email:             abhiram@cs.utah.edu

# Custom vars
version:             1.0.0
